import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ApodProvider } from "./Apod/ApodContext.js";
import { NeoProvider } from "./Neo/NeoContext.js";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Space Explorer - NASA API Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ApodProvider>
          <NeoProvider>
            {children}
          </NeoProvider>
        </ApodProvider>
      </body>
    </html>
  );
}
